name: Publish to TestPyPI

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags
  workflow_dispatch:

jobs:
  publish-testpypi:
    runs-on: ubuntu-latest
    environment: testpypi  # Must match TestPyPI publisher config
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Build package
      run: |
        python -m pip install build
        python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        trusted-publisher: true